### ISSUE TITLE
Android how to create view like this in Circular shape having imageview and text view

### ISSUE THREAD

**Issue by achinverma** [amulyakhare/TextDrawable#12]
i want to create a view like this , i will post picture ,is it possible with your library. please guide me.
![untitled](https://cloud.githubusercontent.com/assets/2811593/5772324/bdd9eef2-9d76-11e4-94ce-be3022f228b2.png)

**Comment by amulyakhare** [comment]
I think it will be very hard to achieve something like this using the library. You could however, look at the source code and modify it to fit your custom needs.
