### ISSUE TITLE
Using AAR from gradle overrides app launcher icons

### ISSUE THREAD

**Issue by pulimento** [amulyakhare/TextDrawable#3]
When using as a BinTray dependency in Android Studio v1.0.1, app gets its main icon (ic_launcher) from this library instead of app's default icon. This results in app appearing with android-robot default icon.

I've found posts in StackOverflow regarding this issue, but proposed solutions not worked from me.

Please, remove ic_launcher icons from the generated AAR library. Thanks

**Comment by jenzz** [comment]
I [forked](https://github.com/jenzz/TextDrawable) this repo and fixed the issue by removing all the `ic_launcher` drawables.

I don't wanna steel any glory from the author but I've built the .aar file for this library and uploaded it to [my local maven repo](https://github.com/jenzz/jenzz-mvn-repo) here on GitHub. Once this library has the issue fixed or if the author will ask me to I will erase the library from my repo right away.

If you wanna use it, you can include it like this:
```
repositories {
    ...
    maven { url 'https://github.com/jenzz/jenzz-mvn-repo/raw/master/releases' }
}

dependencies {
    ...
    compile 'com.amulyakhare:com.amulyakhare.textdrawable:1.0.0'
}
```

**Comment by pulimento** [comment]
Thanks! @amulyakhare i'm closing this issue now

**Comment by amulyakhare** [comment]
Hi guys,

I am sorry that I have not been able to maintain this project for some time now. I was extremely busy with something else. I have uploaded a new version of the `.aar`. Will try my best to keep things updated in the future. 

Regards,
-Amulya
