### ISSUE TITLE
This library is not working at all

### ISSUE THREAD

**Issue by puneetagarwal** [amulyakhare/TextDrawable#48]
Hello,

I tried using this library for showing user initials in my app. But unfortunately, it seems that the library is not working and the code is broken. When I used it, it just shows a blank area where my ImageView is placed. 

Can you tell me that are you going to fix this library because there is no use of putting a library on Git which doesn't work at all. Let me know.

**Comment by cobear25** [comment]
@puneetagarwal  You're obviously doing something wrong because it's working for hundreds of other people.
