### ISSUE TITLE
Selected drawable like Gmail

### ISSUE THREAD

**Issue by AkshayChordiya** [amulyakhare/TextDrawable#6]
Hey, 

Thank for such an amazing & simple to use library. I was checking the screenshots in the Readme & 2nd screenshot got my attention. 
It shows a list of items & few of them are selected & there is a selected image over the image view. I want to achieve that effect. 

Can you tell me how did you achieve it using your library?

**Comment by amulyakhare** [comment]
I do a little trick to get this effect. Basically there are two `ImageView`s that overlap. One shows the text and other has the tick image. Now depending on the user click, I toggle the visibility of the tick. You can find this code here:  

https://github.com/amulyakhare/TextDrawable/blob/master/sample/src/main/java/com/amulyakhare/td/sample/ListActivity.java#L146

This is not the best way to get an effect like this. I use it just for demo purpose.

**Comment by AkshayChordiya** [comment]
@amulyakhare 
Thank you
