### ISSUE TITLE
Can you please publish your library to a Maven Central ? I can offer you some help for this

### ISSUE THREAD

**Issue by dejan2609** [amulyakhare/TextDrawable#80]
Rationale: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
Quote (from a link above):
> May 1st | Bintray, JCenter, GoCenter, and ChartCenter services will no longer be available

Further more: it seems that Signal Android app depends on this library (fetched via Bintray):
https://github.com/signalapp/Signal-Android/blob/v5.3.12/app/build.gradle#L37
```
    maven { // textdrawable
        url 'https://dl.bintray.com/amulyakhare/maven'
        content {
            includeGroupByRegex "com\\.amulyakhare.*"
        }
    }
```

One more note: there is a slim chance that your library is also published to a ***springio-plugins-release*** but I will have to do some more research:
- https://mvnrepository.com/artifact/com.amulyakhare/com.amulyakhare.textdrawable?repo=springio-plugins-release
- https://repo.spring.io/webapp/#/artifacts/browse/tree/General/plugins-release

**Comment by ArcherEmiya05** [comment]
Is there a new artifact now?

**Comment by bpappin** [comment]
I was just coming to file a bug about it not resolving due to the bintray shutdown.

However, realistically, this guy hasn't updated this code since 2015, so I think we are SOL.
IMO It's time for the library to fork, and be taken over by another party.

In the mean time, I'm going to make sure I have a fork, and pull the code local.

**Comment by vipafattal** [comment]
Simply speaking, I think, you could use Jitpack.

**Comment by ChristopheVersieux** [comment]
Trying to update an old project, I also had the issue.  what is the best way to import the library?

**Comment by ramseth001** [comment]
@dejan2609 I have published a fork of the library to Jitpack for my use. Feel free to use it.

[https://github.com/ramseth001/TextDrawable/](https://github.com/ramseth001/TextDrawable/)

**Comment by mendhak** [comment]
This worked for me, with Jitpack enabled, I've used the commit hash from this repo:  

```
implementation 'com.github.amulyakhare:TextDrawable:558677ea31'
```

Be sure to have jitpack in your `repositories` section:

```
maven {
        url "https://jitpack.io"
    }
```

Now let's hope jitpack never shuts down... :sweat_smile: 

(I was unable to go with @ramseth001 's fork as I'm still targetting min SDK 16)

**Comment by dejan2609** [comment]
JCenter was closed on August 15th, 2024. Link: https://jfrog.com/blog/jcenter-sunset
See comments above for solution(s)/workaround(s). 

I'll close this issue now.
