### ISSUE TITLE
Android Gradel Sync Issue.

### ISSUE THREAD

**Issue by RobinKumar5986** [amulyakhare/TextDrawable#86]
Could not find com.amulyakhare:com.amulyakhare.textdrawable:1.0.1.
Required by:
    project :app

getting this issue  in android studio how to fix this ?

**Comment by NilayTheAndroidGuy** [comment]
Does someone have any resolution for this? I am getting this exact issue when I migrated Gradle to 8.4.2

**Comment by mendhak** [comment]
I've been using the commit rather than the tag which seems to work:

    implementation 'com.github.amulyakhare:TextDrawable:558677ea31'

Through jitpack in repositories section:

```
maven {
        url "https://jitpack.io"
    }
```

**Comment by RobinKumar5986** [comment]
I went to check on maven and found that these library is not present. I tried to download the the jar file directly from maven but  not able to to. I tried multiple websites to do but not able to do. Do, any one have solution for these ???

**Comment by mores** [comment]
The original artifact was published to bintray.com.

JFrog decided to shutdown bintray.com: https://jfrog.com/blog/jcenter-sunset/#:~:text=When%20Bintray%20was%20deprecated%20on,to%20migrate%20to%20other%20public

Someone now needs to publish this artifact to Maven Central.

I plan to do this unless someone beats me to it.

**Comment by mores** [comment]
change 'com.amulyakhare:com.amulyakhare.textdrawable:1.0.1' to 'io.github.mores:textdrawable:1.0.1'

**Comment by RobinKumar5986** [comment]
@mores thanks for putting this.

**Comment by RobinKumar5986** [comment]
Closing this issue for now.
